# Generated by Django 5.2.8 on 2026-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=200)),
                ('qr_code_img', models.ImageField(upload_to='qr_codes/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
